//--->>Types for Employee Availability ---->>>
export const FETCH_EMPLOYEE_AVAILABILITY_SUCCESS = 'FETCH_EMPLOYEE_AVAILABILITY_SUCCESS';
export const FETCH_EMPLOYEE_AVAILABILITY_REQUESTING = 'FETCH_EMPLOYEE_AVAILABILITY_REQUESTING';
export const FETCH_EMPLOYEE_AVAILABILITY_FAIL = 'FETCH_EMPLOYEE_AVAILABILITY_FAIL';

//--->>Types for Save Update Employee Availability---->>>
export const SAVE_UPDATE_EMPLOYEE_AVAILABILITY_SUCCESS = 'SAVE_UPDATE_EMPLOYEE_AVAILABILITY_SUCCESS';
export const SAVE_UPDATE_EMPLOYEE_AVAILABILITY_REQUESTING = 'SAVE_UPDATE_EMPLOYEE_AVAILABILITY_REQUESTING';
export const SAVE_UPDATE_EMPLOYEE_AVAILABILITY_FAIL = 'SAVE_UPDATE_EMPLOYEE_AVAILABILITY_FAIL';

//--->>Types for Delete Employee Availability---->>>
export const DELETE_EMPLOYEE_AVAILABILITY_SUCCESS = 'DELETE_EMPLOYEE_AVAILABILITY_SUCCESS';
export const DELETE_EMPLOYEE_AVAILABILITY_REQUESTING = 'DELETE_EMPLOYEE_AVAILABILITY_REQUESTING';
export const DELETE_UPDATE_EMPLOYEE_AVAILABILITY_FAIL = 'DELETE_UPDATE_EMPLOYEE_AVAILABILITY_FAIL';

