
//--->>Types for Reasons---->>>
export const FETCH_REASONS_SUCCESS = 'FETCH_REASONS_SUCCESS';
export const FETCH_REASONS_REQUESTING = 'FETCH_REASONS_REQUESTING';
export const FETCH_REASONS_FAIL = 'FETCH_REASONS_FAIL';

//--->>Types for Get Employee Hours---->>>
export const FETCH_EMPLOYEE_HOURS_SUCCESS = 'FETCH_EMPLOYEE_HOURS_SUCCESS';
export const FETCH_EMPLOYEE_HOURS_REQUESTING = 'FETCH_EMPLOYEE_HOURS_REQUESTING';
export const FETCH_EMPLOYEE_HOURS_FAIL = 'FETCH_EMPLOYEE_HOURS_FAIL';

//--->>Types for Get Employee Basic Details ---->>>
export const FETCH_EMPLOYEE_BASIC_DETAILS_SUCCESS = 'FETCH_EMPLOYEE_BASIC_DETAILS_SUCCESS';
export const FETCH_EMPLOYEE_BASIC_DETAILS_REQUESTING = 'FETCH_EMPLOYEE_BASIC_DETAILS_REQUESTING';
export const FETCH_EMPLOYEE_BASIC_DETAILS_FAIL = 'FETCH_EMPLOYEE_BASIC_DETAILS_FAIL';

//--->>Types for Get Employee Guest Feedback ---->>>
export const FETCH_EMPLOYEE_GUEST_FEEDBACK_SUCCESS = 'FETCH_EMPLOYEE_GUEST_FEEDBACK_SUCCESS';
export const FETCH_EMPLOYEE_GUEST_FEEDBACK_REQUESTING = 'FETCH_EMPLOYEE_GUEST_FEEDBACK_REQUESTING';
export const FETCH_EMPLOYEE_GUEST_FEEDBACK_FAIL = 'FETCH_EMPLOYEE_GUEST_FEEDBACK_FAIL';

//--->>Types for Get Employee Guest Feedback ---->>>
export const FETCH_EMPLOYEE_PERSONAL_DETAILS_SUCCESS = 'FETCH_EMPLOYEE_PERSONAL_DETAILS_SUCCESS';
export const FETCH_EMPLOYEE_PERSONAL_DETAILS_REQUESTING = 'FETCH_EMPLOYEE_PERSONAL_DETAILS_REQUESTING';
export const FETCH_EMPLOYEE_PERSONAL_DETAILS_FAIL = 'FETCH_EMPLOYEE_PERSONAL_DETAILS_FAIL';

//--->>Types for Update Employee Personal Details ---->>>
export const UPDATE_EMPLOYEE_PERSONAL_DETAILS_SUCCESS = 'UPDATE_EMPLOYEE_PERSONAL_DETAILS_SUCCESS';
export const UPDATE_EMPLOYEE_PERSONAL_DETAILS_REQUESTING = 'UPDATE_EMPLOYEE_PERSONAL_DETAILS_REQUESTING';
export const UPDATE_EMPLOYEE_PERSONAL_DETAILS_FAIL = 'UPDATE_EMPLOYEE_PERSONAL_DETAILS_FAIL';

export const GET_NOTIFICATION_LIST_REQUESTING = 'GET_NOTIFICATION_LIST_REQUESTING'
export const GET_NOTIFICATION_LIST_SUCCESS = 'GET_NOTIFICATION_LIST_SUCCESS'
export const GET_NOTIFICATION_LIST_FAIL = 'GET_NOTIFICATION_LIST_FAIL'

export const GET_END_EMPLOYEEMENT_REASON_REQUESTING = 'GET_END_EMPLOYEEMENT_REASON_REQUESTING'
export const GET_END_EMPLOYEEMENT_REASON_SUCCESS = 'GET_END_EMPLOYEEMENT_REASON_SUCCESS'
export const GET_END_EMPLOYEEMENT_REASON_FAIL = 'GET_END_EMPLOYEEMENT_REASON_FAIL'

export const SAVE_UPDATE_USER_DEVICES_REQUESTING = 'SAVE_UPDATE_USER_DEVICES_REQUESTING'
export const SAVE_UPDATE_USER_DEVICES_SUCCESS = 'SAVE_UPDATE_USER_DEVICES_SUCCESS'
export const SAVE_UPDATE_USER_DEVICES_FAIL = 'SAVE_UPDATE_USER_DEVICES_FAIL'

export const GET_NOTIFICATION_DETAILS_REQUESTING = 'GET_NOTIFICATION_DETAILS_REQUESTING'
export const GET_NOTIFICATION_DETAILS_SUCCESS = 'GET_NOTIFICATION_DETAILS_SUCCESS'
export const GET_NOTIFICATION_DETAILS_FAIL = 'GET_NOTIFICATION_DETAILS_FAIL'