//--->>Types for Employee Time Off ---->>>
export const CREATE_EMPLOYEE_TIME_OFF_SUCCESS = 'CREATE_EMPLOYEE_TIME_OFF_SUCCESS';
export const CREATE_EMPLOYEE_TIME_OFF_REQUESTING = 'CREATE_EMPLOYEE_TIME_OFF_REQUESTING';
export const CREATE_EMPLOYEE_TIME_OFF_FAIL = 'CREATE_EMPLOYEE_TIME_OFF_FAIL';

export const GET_MY_SCHEDULE_REQUESTING = 'GET_MY_SCHEDULE_REQUESTING';
export const GET_MY_SCHEDULE_SUCCESS = 'GET_MY_SCHEDULE_SUCCESS';
export const GET_MY_SCHEDULE_FAIL = 'GET_MY_SCHEDULE_FAIL';

export const GET_EMPLOYEE_STORE_REQUESTING = 'GET_EMPLOYEE_STORE_REQUESTING';
export const GET_EMPLOYEE_STORE_SUCCESS = 'GET_EMPLOYEE_STORE_SUCCESS';
export const GET_EMPLOYEE_STORE_FAIL = 'GET_EMPLOYEE_STORE_FAIL';

export const OPEN_SHIFT_REQUESTING = 'OPEN_SHIFT_REQUESTING';
export const OPEN_SHIFT_SUCCESS = 'OPEN_SHIFT_SUCCESS';
export const OPEN_SHIFT_FAIL = 'OPEN_SHIFT_FAIL';

export const GET_PENDING_SWAP_REQUEST_DETAILS_REQUESTING = 'GET_PENDING_SWAP_REQUEST_DETAILS_REQUESTING';
export const GET_PENDING_SWAP_REQUEST_DETAILS_SUCCESS = 'GET_PENDING_SWAP_REQUEST_DETAILS_SUCCESS';
export const GET_PENDING_SWAP_REQUEST_DETAILS_FAIL = 'GET_PENDING_SWAP_REQUEST_DETAILS_FAIL';

export const ACCEPT_SWAP_REQUEST_REQUESTING = 'ACCEPT_SWAP_REQUEST_REQUESTING';
export const ACCEPT_SWAP_REQUEST_SUCCESS = 'ACCEPT_SWAP_REQUEST_SUCCESS';
export const ACCEPT_SWAP_REQUEST_FAIL = 'ACCEPT_SWAP_REQUEST_FAIL';

export const DECLINE_SWAP_REQUEST_REQUESTING = 'DECLINE_SWAP_REQUEST_REQUESTING';
export const DECLINE_SWAP_REQUEST_SUCCESS = 'DECLINE_SWAP_REQUEST_SUCCESS';
export const DECLINE_SWAP_REQUEST_FAIL = 'DECLINE_SWAP_REQUEST_FAIL';

export const DELETE_EMPLOYEE_OPEN_SHIFT_REQUEST = 'DELETE_EMPLOYEE_OPEN_SHIFT_REQUEST';
export const DELETE_EMPLOYEE_OPEN_SHIFT_SUCCESS = 'DELETE_EMPLOYEE_OPEN_SHIFT_SUCCESS';
export const DELETE_EMPLOYEE_OPEN_SHIFT_FAIL = 'DELETE_EMPLOYEE_OPEN_SHIFT_FAIL'

export const GET_MY_SCHEDULE_HISTORY_REQUEST = 'GET_MY_SCHEDULE_HISTORY_REQUEST';
export const GET_MY_SCHEDULE_HISTORY_SUCCESS = 'GET_MY_SCHEDULE_HISTORY_SUCCESS';
export const GET_MY_SCHEDULE_HISTORY_FAIL = 'GET_MY_SCHEDULE_HISTORY_FAIL';

export const GET_LEAVE_TYPE_LIST_REQUEST = 'GET_LEAVE_TYPE_LIST_REQUEST';
export const GET_LEAVE_TYPE_LIST_SUCCESS = 'GET_LEAVE_TYPE_LIST_SUCCESS';
export const GET_LEAVE_TYPE_LIST_FAIL = 'GET_LEAVE_TYPE_LIST_FAIL';