//--->>Types for Employee Time Off ---->>>
export const GET_STORE_LIST_SUCCESS = 'GET_STORE_LIST_SUCCESS';
export const GET_STORE_LIST_REQUESTING = 'GET_STORE_LIST_SUCCESS_REQUESTING';
export const GET_STORE_LIST_SUCCESS_FAIL = 'GET_STORE_LIST_SUCCESS_FAIL';

export const GET_STORE_SCHEDULE_REQUESTING = 'GET_STORE_SCHEDULE_REQUESTING'
export const GET_STORE_SCHEDULE_SUCCESS = 'GET_STORE_SCHEDULE_SUCCESS'
export const GET_STORE_SCHEDULE_FAIL = 'GET_STORE_SCHEDULE_FAIL'

export const GET_ALL_STORE_LIST_REQUESTING = 'GET_ALL_STORE_LIST_REQUESTING'
export const GET_ALL_STORE_LIST_SUCCESS = 'GET_ALL_STORE_LIST_SUCCESS'
export const GET_ALL_STORE_LIST_FAIL = 'GET_ALL_STORE_LIST_FAIL'

export const GET_AVAILABLE_SHIFT_REQUESTING = 'GET_AVAILABLE_SHIFT_REQUESTING'
export const GET_AVAILABLE_SHIFT_SUCCESS = 'GET_AVAILABLE_SHIFT_SUCCESS'
export const GET_AVAILABLE_SHIFT_FAIL = 'GET_AVAILABLE_SHIFT_FAIL'

export const OFFER_OPENED_SHIFT_REQUESTING = 'OFFER_OPENED_SHIFT_REQUESTING'
export const OFFER_OPENED_SHIFT_SUCCESS = 'OFFER_OPENED_SHIFT_SUCCESS'
export const OFFER_OPENED_SHIFT_FAIL = 'OFFER_OPENED_SHIFT_FAIL'

export const COVER_SHIFT_REQUESTING = 'COVER_SHIFT_REQUESTING'
export const COVER_SHIFT_SUCCESS = 'COVER_SHIFT_SUCCESS'
export const COVER_SHIFT_FAIL = 'COVER_SHIFT_FAIL'